FROM node:7.7.1-alpine
RUN npm -g install bower gulp grunt phantomjs webpack
RUN echo 'Here are your build tools. Even old stuff.'
RUN echo 'This is a new line in the dockerfile. Will it take as long this time?'
